name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./application/pom.xml
          mvn clean package -f ./issue/pom.xml
          mvn clean package -f ./alarm/pom.xml
          mvn clean package -f ./integration/pom.xml
          mvn clean package -f ./edms/pom.xml

      - name: Docker Build and push for Application
        uses: docker/build-push-action@v4
        with:
          context: ./application
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/application:latest
            ghcr.io/${{ github.repository }}/application:${{ github.ref_name }}
            
      - name: Docker Build and push for Issue
        uses: docker/build-push-action@v4
        with:
          context: ./issue
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/issue:latest
            ghcr.io/${{ github.repository }}/issue:${{ github.ref_name }}
            
      - name: Docker Build and push for Alarm
        uses: docker/build-push-action@v4
        with:
          context: ./alarm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/alarm:latest
            ghcr.io/${{ github.repository }}/alarm:${{ github.ref_name }}
            
      - name: Docker Build and push for Integration
        uses: docker/build-push-action@v4
        with:
          context: ./integration
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/integration:latest
            ghcr.io/${{ github.repository }}/integration:${{ github.ref_name }}
            
      - name: Docker Build and push for Edms
        uses: docker/build-push-action@v4
        with:
          context: ./edms
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/edms:latest
            ghcr.io/${{ github.repository }}/edms:${{ github.ref_name }}
            
