apiVersion: apps/v1
kind: Deployment
metadata:
  name: edms
  labels:
    app: edms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edms
  template:
    metadata:
      labels:
        app: edms
    spec:
      containers:
        - name: edms
          image: "username/edms:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
